"""Job model (tasks with status, priority, assignment)."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, Text, text
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from nebula_models.base import Base, TimestampMixin


class Job(Base, TimestampMixin):
    """Async task/workflow with generated ID format YYYYQ#-XXXX."""

    __tablename__ = "jobs"

    # Custom text ID, not UUID (generated by generate_job_id() function)
    id: Mapped[str] = mapped_column(
        Text, primary_key=True, server_default=text("generate_job_id()")
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    assigned_to: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    agent_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("agents.id")
    )
    status_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("statuses.id")
    )
    priority: Mapped[str | None] = mapped_column(String)
    parent_job_id: Mapped[str | None] = mapped_column(Text, ForeignKey("jobs.id"))
    due_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    privacy_scope_ids: Mapped[list[uuid.UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), server_default=text("'{}'"), nullable=False
    )
    # No metadata column - replaced by context-of relationships (migration 021)

    status = relationship("Status", lazy="joined")
    agent = relationship("Agent", lazy="joined")
    parent_job = relationship("Job", remote_side="Job.id", lazy="select")
